/**
 * Shared types — re-exports from @/types for convenience.
 * Import from here when you only need types, not the full @/types barrel.
 */
export type {
  User,
  TokenPair,
  LoginResponse,
  LoginMethod,
  Agent,
  Message,
  MessageContent,
  Conversation,
  ConversationDetail,
  StreamEvent,
  FileItem,
  WsAdapter,
  WorkspaceFile,
  WorkspaceFileVersion,
  ConfirmationRequest,
  RtAgentMeta,
  RoundtableReply,
  RoundtableContent,
  Team,
  Member,
  Knowledge,
  ActivityItem,
  ConversationBrief,
  TeamStats,
  TeamDetail,
  PermissionItem,
  PermissionGroup,
  TeamPolicy,
  Project,
  ProjectDoc,
  ProjectDetail,
  Task,
  AdminStats,
  AdminRole,
  RolesMatrix,
  AuditEntry,
  SystemSettings,
  IdentityProvider,
  DeptMapping,
  ProviderInfo,
} from "@/types";
